# Generated by Django 4.0.4 on 2022-04-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('HP', 'Hip Hop'), ('SL', 'Soul'), ('RK', 'Rock'), ('ML', 'Metal')], max_length=5, null=True),
        ),
    ]
